sudo: false
language: node_js
node_js:
  - 14 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - master # build development branch only
script:
  - hexo generate # generate static files
deploy:
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  target-branch: master #部署到master分支
  on:
    branch: development
  local-dir: public

